### ISSUE TITLE
lat/lon order in _fault.txt files

### ISSUE THREAD

**Issue by kmarano-usgs** [usgs/shakemap#662] opened 2018-06-21 18:24 UTC
In order to process _fault.txt files correctly, the coordinates need to be given as
lon lat depth

This is a recent change and I believe it is in error. Older style fault text files with the [lat lon depth] order have previously been read by the code without issue.

**Comment by mhearne-usgs** [comment] 2018-06-22 00:38
Actually, it is not in error - we're moving towards a standard where coordinates are passed in x,y order, regardless of whether those are cartesian coordinates or lon, lat values. The old files can sometimes be read, but generally speaking ShakeMap 4.0 is less "tolerant" about deviations from the rules than 3.5.

Is there a specific file that won't load?

**Comment by kmarano-usgs** [comment] 2018-06-22 19:20
We're having issues with any and all ShakeMap 3.5-style fault.txt files, including ones that worked with previous versions of the ShakeMap 4.0 code (pre-SSA up through the first workshop). I can put examples on FTP.

**Comment by emthompson-usgs** [comment] 2018-06-25 14:50
Also, it might be easiest to just attach a problem file to a comment here on github rather than deal with the ftp server. I think this might be an issue with where the fault reader is getting called. [This](https://github.com/usgs/shakemap/blob/master/shakelib/rupture/factory.py#L236) is the method that does the parsing; if `new_format` is True then it expects x, y, z order, otherwise it expects y, x, z order. Also, if you send us the error message you are getting, it might help us know if the problem is the order of the coordinates or other problems. As Mike pointed out, we discovered that ShakeMap 3.5 was "accepting" fault files that actually had errors in them and should have been rejected.

**Comment by kmarano-usgs** [comment] 2018-06-25 16:41
There are no errors when running, it's a matter of improper output.

Using intensity data and this fault (lat lon depth):
#Source: Mercado and McCann (1998)
>
18.58 -67.42 2.309
18.44 -67.5 2.309
18.44 -67.5 22.2
18.58 -67.42 22.2
18.58 -67.42 2.309
>
18.86 -67.38 4.336
18.58 -67.42 4.336
18.58 -67.42 27.1
18.86 -67.38 27.1
18.86 -67.38 4.336
>
18.88 -67.35 4.712
18.86 -67.38 4.712
18.86 -67.38 17.6
18.88 -67.35 17.6
18.88 -67.35 4.712
>
19.00 -67.34 4.674
18.88 -67.35 4.674
18.88 -67.35 27.6
19.00 -67.34 27.6
19.00 -67.34 4.674

Run on 5/18/18:
![intensity](https://user-images.githubusercontent.com/26940012/41863400-dddb91b2-7863-11e8-8b14-2f5f1b5defaf.jpg)

Run 6/21/18:
![intensity](https://user-images.githubusercontent.com/26940012/41863414-f1aab4fc-7863-11e8-8f4d-94c5d037d1cf.jpg)

Fault file with lat/lon order reversed (lon lat depth), 6/21/18:
![intensity](https://user-images.githubusercontent.com/26940012/41863417-fa312cd2-7863-11e8-8a18-b0710b0e01db.jpg)


Another example.
Using this fault (lat lon depth), no intensity data:
33.2956 -80.2067 5.0000
32.7313 -80.4144 5.0000
32.7313 -80.4144 30.0000
33.2956 -80.2067 30.0000
33.2956 -80.2067 5.0000

Output:
![intensity](https://user-images.githubusercontent.com/26940012/41863139-216873a6-7863-11e8-9028-46bc9b6cf8d1.jpg)

Switching lat/lon:
![intensity](https://user-images.githubusercontent.com/26940012/41863159-30a976f8-7863-11e8-8385-a99eb48f8f80.jpg)

**Comment by cbworden** [comment] 2018-06-25 18:59
The text_to_json function has the "new_format" argument, but I don't see that that argument is ever used anywhere (except the tests). That is, we don't appear to have an automatic (or even manual) way to tell the factory function get_rupture() that a file is of one type or the other. I'm not sure what the intent was, but maybe some code that compares the epicenter to the fault coordinates could distinguish between the the old and new formats, and then call text_to_json() with the appropriate argument.

**Comment by emthompson-usgs** [comment] 2018-06-25 19:13
It actually gets set to False in [sm_create](https://github.com/usgs/shakemap/blob/1c707928f027a60af70cf89acfa82b65d72f3833/bin/sm_create#L232) and [sm_migrate](https://github.com/usgs/shakemap/blob/b2888b4cca3a9d031b683bcf2e294e45d4d248b6/bin/sm_migrate#L301). I believe that the thinking was that if you are using one of those tools and the shakemap is based on an existing event then it would be an "old" format with y, x, z order vertices. I'm not sure why that isn't working for Kristin. We'll have to look into it.

**Comment by emthompson-usgs** [comment] 2018-06-25 21:41
For the record, the fundamental problem here appears to have been that `sm_migrate` never reached the code that handles ruptures and so the original *_fault.txt files were left in place unmodified. This was because the event id was not being handled correctly (it was being tracked in the `alleventids` list but after that list was populated, it would prepend the netid before creating the event directory. Then it would go looking for the directories in `alleventids` and could not find them because they didn't exist. Additionally, a few spurious events were getting created because event id was taken incorrectly from the file path. About 3 atlas events do still fail because of incorrect specification of vertices and will have to be fixed manually.

**Closed** 2018-06-25 21:50 UTC
