### ISSUE TITLE
Test install on CentOS

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#560] opened 2018-05-19 02:03 UTC
One anecdotal report of issues on this version of Linux

**Comment by hadighasemi** [comment] 2018-06-07 05:08
Hi Bruce, 

With GA's SM4.0 installation on CentOs, I managed to fix the bugs (issues) as detailed below. (at least I think that I have fixed them :-) 
Initially with running "py.test" I was receiving 5 F for "rupture_test", "container_test", and "products_test". In addition the "mapping" module was producing error.  I fixed the errors by modifying the following lines:

1. editing the "~/shakelib/rupture/factory.py" as follows:
    - line 60: 
       > except (UnicodeDecodeError,json.decoder.JSONDecodeError) as e:

    -  line 275:
       > f = open(file, 'rt',errors='ignore') 

2. editing the "/home/centos/miniconda/envs/shakemap/lib/python3.5/site-packages/mapio/city.py":
    - line 104:
      > f = open(cityfile,'rt',errors='ignore')

after above modifications, the "py.test" runs smoothly without any error messages. I was also able to successfully run "shake" command for couple of examples :)

Please let me know if above changes make sense to you!

**Comment by emthompson-usgs** [comment] 2018-06-07 14:35
@hadighasemi Thanks for the report. Can you send us the output of `locale` on your system? We are thinking that although you are getting the code to run with those changes, it might be a better solution to change the locale settings. Here's the output on my system that is not having these issues: 
```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by hadighasemi** [comment] 2018-06-07 22:42
Hi @emthompson-usgs

**Comment by hadighasemi** [comment] 2018-06-08 01:13
Thanks @emthompson-usgs for the hint.
Actually I had tried export LANG="en_US.UTF-8" before but encountered same errors. the issue is now fixed, more properly this time :), by adding the following to my .bashrc:

``` export LC_ALL=en_US.UTF-8 ``` 

to make sure the above changes were effective:

``` >>> import sys
>>> sys.stdout.encoding
'UTF-8'  
``` 
and here is the output of py.test
```
============================================================== warnings summary ===============================================================
tests/shakelib/distance_test.py::test_distance_no_rupture
  /home/centos/shakemap_src/shakelib/rupture/point_rupture.py:236: UserWarning: Unsupported tectonic region; using coefficients for unknowntectonic region.
    'Unsupported tectonic region; using coefficients for unknown'

tests/shakemap/coremods/products_test.py::test_products
  /home/centos/miniconda/envs/shakemap/lib/python3.5/site-packages/mapio/gdal.py:442: DataSetWarning: 'Down-casting double precision floating point to single precision'
    warnings.warn(DataSetWarning('Down-casting double precision floating point to single precision'))
  /home/centos/miniconda/envs/shakemap/lib/python3.5/site-packages/numpy/ma/core.py:6385: MaskedArrayFutureWarning: In the future the default for ma.minimum.reduce will be axis=0, not the current None, to match np.minimum.reduce. Explicitly pass 0 or None to silence this warning.
    return self.reduce(a)
  /home/centos/miniconda/envs/shakemap/lib/python3.5/site-packages/numpy/ma/core.py:6385: MaskedArrayFutureWarning: In the future the default for ma.maximum.reduce will be axis=0, not the current None, to match np.maximum.reduce. Explicitly pass 0 or None to silence this warning.
    return self.reduce(a)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
================================================== 107 passed, 4 warnings in 1049.10 seconds ==================================================
```

**Comment by emthompson-usgs** [comment] 2018-06-08 04:13
Okay, great. Those warnings are fine. We will try to add something to the wiki install instructions once we understand clearly when the export LC_ALL setting is needed.

**Closed** 2018-08-13 22:28 UTC
