### ISSUE TITLE
Errors in select

### ISSUE THREAD

**Issue by cbworden** [usgs/shakemap#666] opened 2018-06-26 14:34 UTC
When running the select module on some events, invalid output is generated. These events demonstrate the problem:
```
us1000ehd9
nc73027396
nc73027746
us1000er8i
us1000e0j1
us1000e1r7
us1000db5t
```

For instance, us1000db5t produces this model_zc.conf file (note that the weights don't add up to 1.0):
```
[gmpe_sets]
    [[gmpe_us1000db5t_custom]]
        gmpes = active_crustal_nshmp2014,
        weights = 0.896969543691,
        weights_large_dist = None
        dist_cutoff = nan
        site_gmpes = None
        weights_site_gmpes = None
[modeling]
    gmpe = gmpe_us1000db5t_custom
    mechanism = RS
```
Most of the others do something similar, except us1000ehd9, which produces:
```
[gmpe_sets]
    [[gmpe_us1000ehd9_custom]]
        gmpes = active_crustal_nshmp2014, active_crustal_deep, subduction_crustal, subduction_interface_nshmp2014, subduction_slab_nshmp2014
        weights = 0.141079286641, 0.320634742367, 0.00484913416909, 0.134571492748, 0.398865344075
        weights_large_dist = None
        dist_cutoff = nan
        site_gmpes = None
        weights_site_gmpes = None
[modeling]
    gmpe = gmpe_us1000ehd9_custom
    mechanism = ALL
```
I'm not exactly sure why that fails, but it seems like an odd collection of gmpe sets.

**Comment by emthompson-usgs** [comment] 2018-06-29 16:03
@cbworden This is a really good set of events for checking against because of their complex interaction with subduction zones and other tectonic regions. Here are the new `model_zc.conf` results with my edits to fix bugs. If these look okay then I'll close this issue with the PR that I'm working on now. 

### Event: us1000ehd9
Note, I think this is the same as before and although it is weird it is not wrong. The issue is that this is a deep event in ACR but also near a subduction zone, so it is getting probabilities for ACR, ACR deep, and then also some crustal/interface/slab from the subduction zone. 
```
[gmpe_sets]
    [[gmpe_us1000ehd9_custom]]
        gmpes = active_crustal_nshmp2014, active_crustal_deep, subduction_crustal, subduction_interface_nshmp2014, subduction_slab_nshmp2014
        weights = 0.141079286641, 0.320634742367, 0.00484913416909, 0.134571492748, 0.398865344075
        weights_large_dist = None
        dist_cutoff = nan
        site_gmpes = None
        weights_site_gmpes = None
[modeling]
    gmpe = gmpe_us1000ehd9_custom
    mechanism = ALL
```
### Event: nc73027396
```
[gmpe_sets]
    [[gmpe_nc73027396_custom]]
        gmpes = active_crustal_california, subduction_crustal
        weights = 0.567010250574, 0.432989749426
        weights_large_dist = None
        dist_cutoff = nan
        site_gmpes = None
        weights_site_gmpes = None
[modeling]
    gmpe = gmpe_nc73027396_custom
    mechanism = SS
```
### Event: nc73027746
```
[gmpe_sets]
    [[gmpe_nc73027746_custom]]
        gmpes = active_crustal_california, subduction_crustal
        weights = 0.658621191019, 0.341378808981
        weights_large_dist = None
        dist_cutoff = nan
        site_gmpes = None
        weights_site_gmpes = None
[modeling]
    gmpe = gmpe_nc73027746_custom
    mechanism = SS
```
### Event: us1000er8i
```
[gmpe_sets]
    [[gmpe_us1000er8i_custom]]
        gmpes = active_crustal_nshmp2014, subduction_crustal
        weights = 0.592525025445, 0.407474974555
        weights_large_dist = None
        dist_cutoff = nan
        site_gmpes = None
        weights_site_gmpes = None
[modeling]
    gmpe = gmpe_us1000er8i_custom
    mechanism = SS
```
### Event: us1000e0j1
```
[gmpe_sets]
    [[gmpe_us1000e0j1_custom]]
        gmpes = active_crustal_nshmp2014, subduction_crustal
        weights = 0.869366839187, 0.130633160813
        weights_large_dist = None
        dist_cutoff = nan
        site_gmpes = None
        weights_site_gmpes = None
[modeling]
    gmpe = gmpe_us1000e0j1_custom
    mechanism = ALL
```
### Event: us1000e1r7 (nc73014276)
```
[gmpe_sets]
    [[gmpe_nc73014276_custom]]
        gmpes = active_crustal_california, subduction_crustal
        weights = 0.639157847873, 0.360842152127
        weights_large_dist = None
        dist_cutoff = nan
        site_gmpes = None
        weights_site_gmpes = None
[modeling]
    gmpe = gmpe_nc73014276_custom
    mechanism = ALL
```
### Event: us1000db5t
```
[gmpe_sets]
    [[gmpe_us1000db5t_custom]]
        gmpes = active_crustal_nshmp2014, subduction_crustal
        weights = 0.896969543691, 0.103030456309
        weights_large_dist = None
        dist_cutoff = nan
        site_gmpes = None
        weights_site_gmpes = None
[modeling]
    gmpe = gmpe_us1000db5t_custom
    mechanism = RS
```

**Closed** 2018-06-29 21:59 UTC
Labels: bug, in progress
