### ISSUE TITLE
static map bounds for Hawaii

### ISSUE THREAD

**Issue by brianshiro** [usgs/shakemap#918] opened 2019-03-01 21:38 UTC
The automatic map bounds for the static intensity maps appear to always be centered on the earthquake epicenter.  In some geographic contexts this may not be appropriate.  For example, in Hawaii the large seismic sources are all in the southeastern portion of the state, but the land and population centers are all offset to the northwest.  When the maps are centered on the epicenter and zoomed out to show shaking intensities hundreds of km away, it results in a map with mostly ocean showing and lack of detail in the populated places where it matters most.  Here is an example of an event with a static ShakeMap centered on the epicenter that illustrates the problem: https://earthquake.usgs.gov/archive/product/shakemap/hv61792931/us/1498774362010/download/intensity.jpg

For Hawaii, it might make more sense to fix the southeastern corner of the static maps to a chosen point like 18.5, -154.5.  The other three corners would then just depend on the zoom level, which can be automatically chosen based on the shaking intensity distance from the epicenter.  This would provide a view that appears more "zoomed in" on the areas with land and populated places, making detail more visible.  Here is an example of an event with a static ShakeMap using map bounds like I am describing: https://earthquake.usgs.gov/scenario/product/shakemap-scenario/hvlegacykalapana1975m7p7_se/us/1465526229583/download/intensity.jpg

A corollary to this is to make the DYFI static intensity maps use the same logic and mapping template as the ShakeMap static intensity maps.  We often show these side-by-side and would like them to show the same areas for the same events.  You could recycle the same GMT scripts for both types of maps, for example.

Thanks for considering!
Brian

---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by emthompson-usgs** [comment] 2019-03-01 22:14
We currently support hard coding the extent in the conf file [here](https://github.com/usgs/shakemap/blob/master/shakemap/data/model.conf#L257). It was my understanding that this reproduced the v3 functionality for "zoom maps" but the algorithm you describe is a little bit different. Perhaps it would most logically be combined the with `magnitude_spans` option via an optional config parameter for the center of the map?

**Comment by brianshiro** [comment] 2019-03-01 22:53
Thanks.  Can a user visiting the earthquakes website in order to download maps enter extent coordinates there?  Can those be passed through URL variables via a web service?  If so, that might do the trick.

**Comment by emthompson-usgs** [comment] 2019-03-01 23:41
Thew new USGS webpage has been designed to show the contours on an interactive map, where the user can zoom/pan throughout the map. I think this is a huge improvement because you can zoom into the area you want and I think it takes off some of the pressure to anticipate the best extent for a range of users. The extent in the config file that I sent sets the extent of the the grid for all the ground motion calculations, which ends up being the extend of the static maps that are available in the downloads section. So, so the way I see it is that the most important thing is to make it large enough that it meets everyone's needs and then they can zoom in as needed. Here is an example of what I mean:
https://earthquake.usgs.gov/earthquakes/eventpage/us1000j8fs/shakemap/intensity
But note that the map is not "interactive" until the user clicks on it and so this feature may not be apparent to all users initially.

**Comment by brianshiro** [comment] 2019-03-02 00:06
Does this imply that Hawaii could use an alternate config file on the backend to change the default view, or is there a way for the user to do this?  I'm afraid the interactive maps really aren't very useful to us, only the static ones.

**Comment by cbworden** [comment] 2019-03-02 04:23
Hi, Brian. The new version of ShakeMap does a much better job of controlling the map extent, thanks to an algorithm by Eric. For instance for this event:

https://earthquake.usgs.gov/earthquakes/eventpage/hv70323196/shakemap/intensity

the static map looks like this:

https://earthquake.usgs.gov/archive/product/shakemap/hv70323196/us/1551323397438/download/intensity.jpg

It's possible that a very large event would pull out further, but at some point, to cover the significant shaking in Hawaii, there's going to be a lot of ocean in the map. I agree that the old system covered too large an area, but if we use a fixed extent, we're going to be showing too much most of the time, and if a larger event is not where we expect it to be, we'll miss entirely. I think the new automatic system does a pretty good job of focusing on the (expected) important shaking, and we always have the option of adjusting the bounds of individual earthquakes on an ad-hoc basis. You can contact me, Eric, Kristin Marano (kmarano at usgs dot gov), or Dave Wald and we'll adjust the map.

**Comment by emthompson-usgs** [comment] 2019-03-02 19:26
Brian, I also think that it will be key to run a bunch of your events and see how it looks. If you do that and the new algorithm still seems problematic, I think it wouldn't be unreasonable for us to work with you to tweak things so that it functions to your liking. I think without a concrete example, we have had a difficult time understanding each other thus far in this thread.

**Comment by brianshiro** [comment] 2019-03-05 02:40
That new ShakeMap static map certainly looks nice in terms of shading, and with this extent centering on the map doesn't create the scenario I was describing since you are only showing the Big Island.  For larger events where the zoom extent would be wider, and other islands up the chain are to be shown, that is when it becomes more important not to center the map on the earthquake but rather have the earthquake in the southeastern corner of the map.  The approach I described of fixing the southeastern coordinates and then only floating the other map extent coordinates based on magnitude/distance of shaking would be one way to address this.  I agree that to define this idea further, we'd need to run a batch of events and see how it looks.

**Comment by cbworden** [comment] 2019-03-08 17:17
I'm going to close this issue because it is really a GSM operational issue and not a SM4 development issue. But let's keep an eye on the Hawaii maps and we can implement something to fix the bounds of Hawaii maps if it becomes necessary. Brian, feel free to contact us directly about any issues you see with the HI maps.

**Closed by cbworden** 2019-03-08 17:17 UTC
