### ISSUE TITLE
openblas 0.3.5 causing numerical errors?

### ISSUE THREAD

**Issue by acarapetis** [usgs/shakemap#945] opened 2019-03-28 04:53 UTC
Hey folks,

At GA we're currently testing the integration of our felt reports into ShakeMap. Our prebuilt image (which has a conda environment created in February) has been working consistently, but I've run into an issue today after building a new conda environment. If I include dyfi_dat.xml in my inputs and run assemble & model, I get some kind of numerical error:

    INFO -- 2019-03-28 04:34:20 -- shake.main -- Running command model
    WARNING -- 2019-03-28 04:34:35 -- warnings._showwarnmsg -- 
    /home/centos/shakemap_src/shakemap/coremods/model.py:1069: RuntimeWarning: invalid 
    value encountered in sqrt
      % (imtstr, self.nominal_bias[imtstr], np.sqrt(nom_variance),

Resulting in a totally blown out intensity raster:

![intensity](https://user-images.githubusercontent.com/58440/55130658-c0d64b80-516f-11e9-9d61-182ce8305bb4.jpg)

For reference, how the intensity plot looks using our February machine image:
![intensity](https://user-images.githubusercontent.com/58440/55130982-08a9a280-5171-11e9-9e69-f4a21832ad51.jpg)

Downgrading to the same version of shakemap as in the pre-built image didn't help; so figured the issue was with a dependency. After looking at the diff between the conda environments and downgrading packages randomly for a while, it seems that the culprit is openblas (installed as a dependency of numpy?): downgrading to `openblas=0.3.4` fixed the problem, and conversely upgrading to 0.3.5 on the pre-built image caused the problem to surface there.

Here's the test dataset I'm working with: [muir.zip](https://github.com/usgs/shakemap/files/3016216/muir.zip)

Have you run in to anything like this before? I'm not sure whether this is a bug in openblas/numpy, shakemap relying on a particular library version not pinned in install.sh, or some problem with our dyfi input data. Thoughts?

**Comment by cbworden** [comment] 2019-03-28 15:46
I haven't seen that before, and I can't reproduce it. I did a clean install of the latest ShakeMap software on one of our Linux machines, which included openblas 0.3.5 and it ran your test example without problem. It's possible that we're running different configurations (GMPEs, etc.), or that there is some subtle difference in the versions for different Linux distros or hardware configurations. I suggest doing a clean install today (maybe some dependency took some time to catch up). If the problem persists, send us your model.conf (or model_select.conf if you are using select), and we can try again to reproduce the problem.

**Comment by acarapetis** [comment] 2019-03-29 00:42
Weird. I'm using the default config - to be sure, this morning I spun up a completely fresh CentOS7 install and ran the following script, which reproduced the problem:

    #!/bin/bash -e
    sudo yum install -y bzip2 unzip git curl
    git clone https://github.com/usgs/shakemap
    cd shakemap
    bash install.sh
    source ~/.bashrc # get conda in path
    conda activate shakemap
    sm_profile -c default -a
    cd ~/shakemap_profiles/default/data/
    curl -L https://github.com/usgs/shakemap/files/3016216/muir.zip -o muir.zip
    unzip muir.zip
    shake muir assemble -c '' model mapping

I'll see if it's any different on Ubuntu.

**Comment by acarapetis** [comment] 2019-03-29 02:45
Also reproduced on a fresh Ubuntu Server 18.04 using this script:

#!/bin/bash -e
sudo apt-get install -y bzip2 unzip git curl
git clone https://github.com/usgs/shakemap
cd shakemap
bash install.sh
. ~/miniconda/etc/profile.d/conda.sh
conda activate shakemap
sm_profile -c default -a
cd ~/shakemap_profiles/default/data/
curl -L https://github.com/usgs/shakemap/files/3016216/muir.zip -o muir.zip
unzip muir.zip
shake muir assemble -c '' model mapping

**Comment by cbworden** [comment] 2019-03-29 02:57
Okay, thanks. I'll try to reproduce it on my Mac. We're limited in the OSs we can run here, but maybe I'll try to rig up a test for Travis. For now, I'd say just avoid that version of openblas. If we can't sort it out, we'll put in an exclusion. 

It's an odd error -- the operand of the square root would have to be negative to get it, which means the variance term (the denominator of the bias term) would have to be negative, and that would be hard to do the way the math works.

Oh, and do send along your model.conf or the model_select.conf for that event. Maybe something is going on with the GMPEs.

**Comment by acarapetis** [comment] 2019-03-29 03:32
[Here is our usual model.conf](https://github.com/usgs/shakemap/files/3020991/model.conf.txt); but the simplified reproduction I described in my last comment is just using the default ([this one](https://github.com/usgs/shakemap/blob/master/shakemap/data/model.conf), I guess).

**Comment by cbworden** [comment] 2019-03-29 16:31
I'm not able to reproduce the problem on my Mac. I'd like to understand what is causing this issue, in case it is something in our program logic and not some openblas glitch. It would help if you can trace the issue back to some particular step that is resulting in a negative value. Maybe after this line:

https://github.com/usgs/shakemap/blob/50b9a9f4d31b48411d63bd8a295c5f48be1affd4/shakemap/coremods/model.py#L1190

you could put a print statement and output the values of nom_variance, nom_tau, imtstr, and self.bias_den[imtstr]. That might provide us with a clue as to where things go awry.

**Comment by acarapetis** [comment] 2019-04-01 00:40
`bias_den[imtstr]` is sometimes coming out as large and negative:

    INFO -- 2019-04-01 00:09:50 -- shake.main -- Running command assemble
    INFO -- 2019-04-01 00:09:50 -- shake.main -- Finished running command assemble: Elapsed 0.08 secs
    INFO -- 2019-04-01 00:09:50 -- shake.main -- Running command model
    negative variance found. matrix22 and sigma22inv were dumped to /tmp/SA(3.0)_...
    {'bias_den_imtstr': -912.9198597359813,
     'imtstr': 'SA(3.0)',
     'nom_tau': 0.3499999999999999,
     'nom_variance': -0.0011052696450697436}
    WARNING -- 2019-04-01 00:10:10 -- warnings._showwarnmsg -- /home/centos/shakemap_src/shakemap/coremods/model.py:1219: RuntimeWarning: invalid value encountered in sqrt
      % (imtstr, self.nominal_bias[imtstr], np.sqrt(nom_variance),

    negative variance found. matrix22 and sigma22inv were dumped to /tmp/PGA_...
    {'bias_den_imtstr': -203.23186953874685,
     'imtstr': 'PGA',
     'nom_tau': 0.3499999999999999,
     'nom_variance': -0.005126401575147756}
    negative variance found. matrix22 and sigma22inv were dumped to /tmp/PGV_...
    {'bias_den_imtstr': -1116.4700341776809,
     'imtstr': 'PGV',
     'nom_tau': 0.3499999999999999,
     'nom_variance': -0.0009022772648209729}
    WARNING -- 2019-04-01 00:10:35 -- warnings._showwarnmsg -- /home/centos/shakemap_src/shakemap/coremods/model.py:1608: RuntimeWarning: overflow encountered in exp
      _string_round(np.exp(np.max(self.outgrid[myimt])), 3)

    WARNING -- 2019-04-01 00:10:35 -- warnings._showwarnmsg -- /home/centos/shakemap_src/shakemap/coremods/model.py:1610: RuntimeWarning: overflow encountered in exp
      _string_round(np.exp(np.max(moutgrid[myimt])), 3)

At least some of the problem seems to be in the implementation of `np.linalg.pinv` - openblas 0.3.4 and 0.3.5 are producing fairly similar results for `matrix22` (at least from glancing at the eigenvalues), but 0.3.5 gives a `sigma22inv` with many negative eigenvalues, while 0.3.4's is positive definite. This is true even if I give the exact same matrix to `pinv` under both versions. Could be hardware-related? e.g. [this issue](https://github.com/xianyi/OpenBLAS/issues/1955) seems somewhat similar, and we *are* running on CPUs with AVX-512 support. (I'm not sure whether that support is actually compiled in to the version of openblas we get from conda-forge?)

[Here's an archive](https://github.com/usgs/shakemap/files/3027353/matrices.zip) containing full dump (using `numpy.save`) of matrix22 and sigma22inv for PGA under 0.3.4 and 0.3.5.

**Comment by cbworden** [comment] 2019-04-01 16:27
It must be a hardware-specific thing. I was able to take your 035_PGA_matrix22 and invert it with numpy.linalg.pinv() and the results compare as "True" with np.allclose() to 034_PGA_sigma22inv.
This is on an Intel Linux machine with openblas 0.3.5 from conda-forge. 

I don't think our matrix is particularly tricky -- it's a symmetric, positive definite, covariance matrix. You can actually invert it with numpy.linalg.inv(). In fact, that's something you might want to try. We use pinv because that's the generally recommended approach to the MVN, and is probably a little safer. But you might want to switch the pinv calls with inv and see if things go okay until the openblas bug is fixed. Or you could just downgrade openblas until a fix is found.

**Comment by acarapetis** [comment] 2019-04-03 02:01
We're just going to pin openblas==0.3.4 for now. Thanks for trying to reproduce this on your end. Go ahead and close this issue if you'd like.

**Comment by cbworden** [comment] 2019-04-03 13:32
Sounds good. Sorry it's been a hassle for you. I'll leave this issue open for now in case we learn more or find a workaround.

**Comment by emthompson-usgs** [comment] 2021-02-10 16:30
No updates in almost 2 years. Closing.

**Closed by emthompson-usgs** 2021-02-10 16:30 UTC
