### ISSUE TITLE
vs30 in stationlist.json

### ISSUE THREAD

**Issue by cecialb** [usgs/shakemap#1120] opened 2021-02-10 15:34 UTC
Please describe your issue here:

Hi,
I have a question about vs30 in stationlist.json. I have made Shakemaps for several earthquakes in the same area using the same configuration (GMPE set, IPE, ...), and I have noticed the vs30 value for a given station changes with each earthquake.  For example I get:

Eathquake 1:
```
"type": "Feature",
            "id": "ES.EXGRA",
            "properties": {
                "code": "EXGRA",
                "vs30": 590.79,
```
Earthquake 2:
```
"type": "Feature",
            "id": "ES.EXGRA",
            "properties": {
                "code": "EXGRA",
                "vs30": 513.66,
```

From what I understand: the value of vs30 comes from global_vs30.grd, therefore in predictions you have `"value"` for this vs30, `"value_rock"` for vs30 = 760 m/s and `"value_soil"` for vs30 = 180 m/s. I was expecting to get the same `"vs30"` for a given station, but why do I get slightly different values? Due to interpolation?
I also get a constant vs30 of 760 m/s if the station is more than aprox 80 km away, which I guess comes from `vs30default` if the station is out of the map/grid span?

Another related question: is there a way to include vs30 for a station? I am currently working with global_vs30.grd and want to include measured vs30 values for some stations. I am not sure if I could include this in the _dat.xml files, or maybe using stationlist.json as an input? 

Thank you,
Cecilia

**Comment by emthompson-usgs** [comment] 2021-02-10 15:48
I'll try to address each of your issues:
- I agree that if you are using the same Vs30 grid, then ShakeMap should be giving the same Vs30. I don't think we have enough information to know for sure. Can you send the full list of properties to verify that the lat/lons are identical? Also, can you send the resolutions of the shakemap grid for the two events? 
- The `value_soil` is used for constructing the interactive "regression plot". That requires a constant Vs30 to construct a smooth plot and we allow a "soil" and a "rock" option for the curve. These are the values used for those curves, and are unrelated to the ShakeMap grids. 
- If the station is outside of the map extent, then I suppose that it might be getting the default Vs30 value but I'm not 100% sure. If the station is outside of the map extent, it doesn't affect the ShakeMap grid so this isn't something we would normally worry about. 
- There is no way to include site-specific Vs30 values. This is because the ShakeMap predictions are computed on a mapped grid and it is important that the station Vs30 be consistent with that grid.

**Comment by cecialb** [comment] 2021-02-11 07:57
Sorry, I know I have a lot of questions.

Earthquake 1:
```
"type": "Feature",
			"id": "ES.EXGRA",
			"properties": {
				"code": "EXGRA",
				"name": "EXGRA",
				"instrumentType": "UNK",
				"source": "ES",
				"network": "ES",
				"commType": "UNK",
				"location": "",
				"intensity": 3.6,
				"intensity_flag": "",
				"intensity_stddev": 0.63,
				"pga": 1.677,
				"pgv": 0.6153,
				"distance": 11.143,
				"elev": null,
				"vs30": 590.79,
				"channels": [
					{
						"name": "HNE",
						"amplitudes": [
							{
								"name": "pga",
								"value": 1.229,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "pgv",
								"value": 0.565,
								"units": "cm/s",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(0.3)",
								"value": 1.953,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(1.0)",
								"value": 0.414,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							}
						]
					},
					{
						"name": "HNN",
						"amplitudes": [
							{
								"name": "pga",
								"value": 1.677,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "pgv",
								"value": 0.599,
								"units": "cm/s",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(0.3)",
								"value": 2.273,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(1.0)",
								"value": 0.463,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							}
						]
					},
					{
						"name": "HNZ",
						"amplitudes": [
							{
								"name": "pga",
								"value": 1.792,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "pgv",
								"value": 0.349,
								"units": "cm/s",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(0.3)",
								"value": 1.124,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(1.0)",
								"value": 0.183,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							}
						]
					},
					{
						"name": "--.HNE",
						"amplitudes": [
							{
								"name": "pga",
								"value": 1.1972,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "pgv",
								"value": 0.6153,
								"units": "cm/s",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(0.3)",
								"value": 1.9395,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(1.0)",
								"value": 0.3644,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(3.0)",
								"value": 0.0821,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							}
						]
					},
					{
						"name": "--.HNN",
						"amplitudes": [
							{
								"name": "pga",
								"value": 1.6623,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "pgv",
								"value": 0.566,
								"units": "cm/s",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(0.3)",
								"value": 2.307,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(1.0)",
								"value": 0.4928,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(3.0)",
								"value": 0.059,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							}
						]
					},
					{
						"name": "--.HNZ",
						"amplitudes": [
							{
								"name": "pga",
								"value": 1.7965,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "pgv",
								"value": 0.3694,
								"units": "cm/s",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(0.3)",
								"value": 1.1884,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(1.0)",
								"value": 0.2063,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(3.0)",
								"value": 0.0924,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							}
						]
					}
				],
				"station_type": "seismic",
				"nresp": "null",
				"predictions": [
					{
						"name": "sa(0.3)",
						"value": 3.6963,
						"value_rock": 2.995,
						"value_soil": 9.0535,
						"units": "%g",
						"ln_tau": 0.4018,
						"ln_phi": 0.7286,
						"ln_sigma": 0.832,
						"ln_sigma_rock": 0.8336,
						"ln_sigma_soil": 0.7923,
						"ln_bias": -0.8763,
						"ln_bias_sigma": 0.1843
					},
					{
						"name": "sa(1.0)",
						"value": 0.5605,
						"value_rock": 0.4315,
						"value_soil": 1.7867,
						"units": "%g",
						"ln_tau": 0.4714,
						"ln_phi": 0.6287,
						"ln_sigma": 0.7858,
						"ln_sigma_rock": 0.787,
						"ln_sigma_soil": 0.7774,
						"ln_bias": -0.9588,
						"ln_bias_sigma": 0.1741
					},
					{
						"name": "pgv",
						"value": 0.9542,
						"value_rock": 0.7913,
						"value_soil": 2.2012,
						"units": "cm/s",
						"ln_tau": 0.3715,
						"ln_phi": 0.666,
						"ln_sigma": 0.7626,
						"ln_sigma_rock": 0.7633,
						"ln_sigma_soil": 0.7389,
						"ln_bias": -0.9311,
						"ln_bias_sigma": 0.1742
					},
					{
						"name": "sa(3.0)",
						"value": 0.0572,
						"value_rock": 0.0439,
						"value_soil": 0.1873,
						"units": "%g",
						"ln_tau": 0.4905,
						"ln_phi": 0.5819,
						"ln_sigma": 0.761,
						"ln_sigma_rock": 0.7623,
						"ln_sigma_soil": 0.7622,
						"ln_bias": -0.434,
						"ln_bias_sigma": 0.1659
					},
					{
						"name": "pga",
						"value": 2.5064,
						"value_rock": 2.2319,
						"value_soil": 4.1383,
						"units": "%g",
						"ln_tau": 0.4179,
						"ln_phi": 0.7197,
						"ln_sigma": 0.8322,
						"ln_sigma_rock": 0.8342,
						"ln_sigma_soil": 0.7901,
						"ln_bias": -0.9763,
						"ln_bias_sigma": 0.1866
					},
					{
						"name": "mmi",
						"value": 3.858,
						"value_rock": 3.7385,
						"value_soil": 4.3917,
						"units": "intensity",
						"tau": 0.2372,
						"phi": 0.76,
						"sigma": 0.7962,
						"sigma_rock": 0.7965,
						"sigma_soil": 0.787,
						"bias": -0.228,
						"bias_sigma": 0.147
					}
				],
				"mmi_from_pgm": [
					{
						"name": "sa(0.3)",
						"value": 3.13,
						"sigma": 0.82,
						"flag": "0"
					},
					{
						"name": "sa(1.0)",
						"value": 4.01,
						"sigma": 0.75,
						"flag": "0"
					},
					{
						"name": "pgv",
						"value": 3.58,
						"sigma": 0.63,
						"flag": "0"
					},
					{
						"name": "sa(3.0)",
						"value": 4.09,
						"sigma": 0.89,
						"flag": "0"
					},
					{
						"name": "pga",
						"value": 3.08,
						"sigma": 0.66,
						"flag": "0"
					}
				],
				"distance_stddev": 1.448,
				"distances": {
					"repi": 11.771,
					"rhypo": 12.147,
					"rjb": 10.62,
					"rjb_var": 1.154,
					"rrup": 11.143,
					"rrup_var": 2.096,
					"rx": 0.0,
					"ry0": 0.0
				}
			},
			"geometry": {
				"type": "Point",
				"coordinates": [
					-3.6052,
					37.1929
				]
			}
		},
```
Earthquake 2:
```
"type": "Feature",
			"id": "ES.EXGRA",
			"properties": {
				"code": "EXGRA",
				"name": "EXGRA",
				"instrumentType": "UNK",
				"source": "ES",
				"network": "ES",
				"commType": "UNK",
				"location": "",
				"intensity": 3.7,
				"intensity_flag": "",
				"intensity_stddev": 0.63,
				"pga": 3.2257,
				"pgv": 0.7973,
				"distance": 11.422,
				"elev": null,
				"vs30": 513.66,
				"channels": [
					{
						"name": "HNE",
						"amplitudes": [
							{
								"name": "pga",
								"value": 3.221,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "pgv",
								"value": 0.777,
								"units": "cm/s",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(0.3)",
								"value": 3.316,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(1.0)",
								"value": 0.195,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							}
						]
					},
					{
						"name": "HNN",
						"amplitudes": [
							{
								"name": "pga",
								"value": 2.304,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "pgv",
								"value": 0.659,
								"units": "cm/s",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(0.3)",
								"value": 2.516,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(1.0)",
								"value": 0.436,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							}
						]
					},
					{
						"name": "HNZ",
						"amplitudes": [
							{
								"name": "pga",
								"value": 2.627,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "pgv",
								"value": 0.639,
								"units": "cm/s",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(0.3)",
								"value": 1.823,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(1.0)",
								"value": 0.163,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							}
						]
					},
					{
						"name": "--.HNE",
						"amplitudes": [
							{
								"name": "pga",
								"value": 3.2257,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "pgv",
								"value": 0.7973,
								"units": "cm/s",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(0.3)",
								"value": 3.6952,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(1.0)",
								"value": 0.2538,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(3.0)",
								"value": 0.0739,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							}
						]
					},
					{
						"name": "--.HNN",
						"amplitudes": [
							{
								"name": "pga",
								"value": 2.3367,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "pgv",
								"value": 0.7191,
								"units": "cm/s",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(0.3)",
								"value": 2.4706,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(1.0)",
								"value": 0.4653,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(3.0)",
								"value": 0.0542,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							}
						]
					},
					{
						"name": "--.HNZ",
						"amplitudes": [
							{
								"name": "pga",
								"value": 2.6394,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "pgv",
								"value": 0.6227,
								"units": "cm/s",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(0.3)",
								"value": 1.8756,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(1.0)",
								"value": 0.1828,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							},
							{
								"name": "sa(3.0)",
								"value": 0.0567,
								"units": "%g",
								"flag": "0",
								"ln_sigma": 0.0
							}
						]
					}
				],
				"station_type": "seismic",
				"nresp": "null",
				"predictions": [
					{
						"name": "sa(1.0)",
						"value": 0.6378,
						"value_rock": 0.4241,
						"value_soil": 1.7557,
						"units": "%g",
						"ln_tau": 0.4714,
						"ln_phi": 0.6336,
						"ln_sigma": 0.7897,
						"ln_sigma_rock": 0.7911,
						"ln_sigma_soil": 0.7815,
						"ln_bias": -0.9276,
						"ln_bias_sigma": 0.1709
					},
					{
						"name": "pgv",
						"value": 1.0391,
						"value_rock": 0.7764,
						"value_soil": 2.16,
						"units": "cm/s",
						"ln_tau": 0.3715,
						"ln_phi": 0.6716,
						"ln_sigma": 0.7675,
						"ln_sigma_rock": 0.7683,
						"ln_sigma_soil": 0.7441,
						"ln_bias": -0.8942,
						"ln_bias_sigma": 0.1715
					},
					{
						"name": "sa(3.0)",
						"value": 0.0653,
						"value_rock": 0.0432,
						"value_soil": 0.1841,
						"units": "%g",
						"ln_tau": 0.4905,
						"ln_phi": 0.5869,
						"ln_sigma": 0.7649,
						"ln_sigma_rock": 0.7663,
						"ln_sigma_soil": 0.7662,
						"ln_bias": -0.4801,
						"ln_bias_sigma": 0.162
					},
					{
						"name": "sa(0.3)",
						"value": 4.0774,
						"value_rock": 2.9426,
						"value_soil": 8.9025,
						"units": "%g",
						"ln_tau": 0.4011,
						"ln_phi": 0.7321,
						"ln_sigma": 0.8348,
						"ln_sigma_rock": 0.8376,
						"ln_sigma_soil": 0.7968,
						"ln_bias": -0.8753,
						"ln_bias_sigma": 0.1811
					},
					{
						"name": "pga",
						"value": 2.621,
						"value_rock": 2.1911,
						"value_soil": 4.0663,
						"units": "%g",
						"ln_tau": 0.417,
						"ln_phi": 0.7237,
						"ln_sigma": 0.8353,
						"ln_sigma_rock": 0.8387,
						"ln_sigma_soil": 0.795,
						"ln_bias": -0.8574,
						"ln_bias_sigma": 0.1829
					},
					{
						"name": "mmi",
						"value": 3.9125,
						"value_rock": 3.7264,
						"value_soil": 4.3796,
						"units": "intensity",
						"tau": 0.2372,
						"phi": 0.7621,
						"sigma": 0.7981,
						"sigma_rock": 0.7984,
						"sigma_soil": 0.789,
						"bias": -0.0146,
						"bias_sigma": 0.1355
					}
				],
				"mmi_from_pgm": [
					{
						"name": "sa(1.0)",
						"value": 3.97,
						"sigma": 0.75,
						"flag": "0"
					},
					{
						"name": "pgv",
						"value": 3.74,
						"sigma": 0.63,
						"flag": "0"
					},
					{
						"name": "sa(3.0)",
						"value": 4.03,
						"sigma": 0.89,
						"flag": "0"
					},
					{
						"name": "sa(0.3)",
						"value": 3.48,
						"sigma": 0.82,
						"flag": "0"
					},
					{
						"name": "pga",
						"value": 3.53,
						"sigma": 0.66,
						"flag": "0"
					}
				],
				"distance_stddev": 1.698,
				"distances": {
					"repi": 11.602,
					"rhypo": 12.634,
					"rjb": 10.398,
					"rjb_var": 1.344,
					"rrup": 11.422,
					"rrup_var": 2.882,
					"rx": 0.0,
					"ry0": 0.0
				}
			},
			"geometry": {
				"type": "Point",
				"coordinates": [
					-3.6052,
					37.1929
				]
			}
		},
```
Grid info: 
(I forced the two events to have the same lon/lat span)
Earthquake 1:
```
"map_information": {
      "grid_points": {
        "longitude": "181",
        "latitude": "145",
        "units": ""
      },
      "grid_spacing": {
        "longitude": "0.0083333",
        "latitude": "0.0083333",
        "units": "degrees"
      },
      "grid_span": {
        "longitude": "1.5",
        "latitude": "1.2",
        "units": "degrees"
      },
      "min": {
        "longitude": "-4.485",
        "latitude": "36.617",
        "units": "degrees"
      },
      "max": {
        "longitude": "-2.985",
        "latitude": "37.817",
        "units": "degrees"
      }
```
Earthquake 2:
```
map_information": {
      "grid_points": {
        "longitude": "181",
        "latitude": "145",
        "units": ""
      },
      "grid_spacing": {
        "longitude": "0.0083333",
        "latitude": "0.0083333",
        "units": "degrees"
      },
      "grid_span": {
        "longitude": "1.5",
        "latitude": "1.2",
        "units": "degrees"
      },
      "min": {
        "longitude": "-4.482",
        "latitude": "36.566",
        "units": "degrees"
      },
      "max": {
        "longitude": "-2.982",
        "latitude": "37.767",
        "units": "degrees"
      }
```

Thanks

**Comment by emthompson-usgs** [comment] 2021-02-11 15:43
Okay, it seems this is not a simple issue. Can you send me the event ids for the two different earthquakes and your station files so I can try to reproduce and hopefully debug this?

**Comment by cecialb** [comment] 2021-02-12 09:08
Yes, sure. Event ids are the file names: 

[es2021bpbpa.zip](https://github.com/usgs/shakemap/files/5970666/es2021bpbpa.zip)
[es2021byudo.zip](https://github.com/usgs/shakemap/files/5970667/es2021byudo.zip)

**Comment by emthompson-usgs** [comment] 2021-02-22 22:39
@cecialb Sorry I have not been able to find time to finish looking into this. 

@cbworden Do you think you can try to figure this out? This issue seems important to resolve.

**Comment by cbworden** [comment] 2021-02-23 00:05
I agree that it is important, and I want to understand it, but I'm buried about six layers deep in ShakeMap right now and I need to dig my way out first. I will get to it as soon as I can.

**Comment by cbworden** [comment] 2021-08-16 16:27
This should be largely fixed in an upcoming release. The issue was, indeed, interpolation of the Vs30 grid to the map extent. I've adjusted the automatic map map extents to fall on a more regular grid, so in many cases this issue will go away, but it will be difficult to resolve it in all cases, especially if users use their own Vs30 maps that don't fall on even 30 arc-second grids.

**Closed by cbworden** 2021-08-16 16:27 UTC
